### ISSUE TITLE
[Bug] pagination `nav` element `width` of `100%` causes horizontal overflow on viewports `<=` widths of `680px`

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/vocabulary#335]
## Description
Issue caused by changes introduced in:
-  #334

## Reproduction

1. Navigate to archive-page context
2. Decrease viewport to `680px` or lower horizontally
3. See error.

## Expectation
The page's right edge should be flush with the window, the extra overflow space should not be present.

## Screenshots
<img width="566" alt="Image" src="https://github.com/user-attachments/assets/755578d1-c0b2-42f5-bcf3-64bdf12edda8" />

## Additional context

This should be fixable by removing the following rule: 

`````css
@media (max-width: 680px) {

    ...

    main nav.pagination {
        width: 100%;
    }

    ...
}

`````

After the padding changes were introduced in #334, the 100% width causes the element to overflow, removing this corrects the issue.

## Resolution

- [x] I would be interested in resolving this bug.
